name: app_resep_makanan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  fluttertoast: ^8.2.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg-createacc.png
    - assets/icons/google_icon.svg
    - assets/icons/arrow_back.svg
    - assets/icons/sun.svg
    - assets/images/card-sample.svg
    - assets/icons/clock.svg
    - assets/icons/fire.svg
    - assets/images/navbar.png
    - assets/icons/search.svg
    - assets/icons/heart.svg
    - assets/icons/blue_heart.svg
    - assets/icons/black_search.svg
    - assets/icons/setting.svg
    - assets/icons/rectangle.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
